### ISSUE TITLE
Broken pipe during RawQuery

### ISSUE THREAD

**Issue by WuTheFWasThat** [the-lambda-church/coquille#42]
I'm getting the following when executing the simple command  `:Coq Check (and True False)`:

```
Error detected while processing function coquille#RawQuery:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jeffwu/Dropbox/dotfiles/vim/bundle/coquille/autoload/coquille.py", line 192, in coq_raw_query
    send_cmd(xml, encoding)
  File "/Users/jeffwu/Dropbox/dotfiles/vim/bundle/coquille/autoload/coquille.py", line 407, in send_cmd
    coqtop.stdin.write(serialized)
IOError: [Errno 32] Broken pipe
```

I thought it was because i was using coq 8.5 (seeing the other issue), but after uninstalling and re-installing, it still happens.

```# coqtop --version                                                                                                                                                [12:35:16 AM]
The Coq Proof Assistant, version 8.3pl5 (March 2015)
compiled on Mar 24 2015 12:04:04 with OCaml 3.12.1
```

**Comment by KitFreddura** [comment]
I'm having the same issue as well. I'm using the latest Coq distro, and have coqide installed. I installed everything through opam if that helps.

**Comment by GiWoongLee** [comment]
I got the same error. I am using coq 8.5pl2 and downloaded all relevant files.

However, I can't solve this error . Please Help me!

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/woong/.vim/bundle/coquille/autoload/coquille.py", line 176, in coq_next
    send_until_fail()
  File "/Users/woong/.vim/bundle/coquille/autoload/coquille.py", line 368, in send_until_
fail
    send_cmd(xml_template, encoding)
  File "/Users/woong/.vim/bundle/coquille/autoload/coquille.py", line 412, in send_cmd
    coqtop.stdin.write(serialized)
IOError: [Errno 32] Broken pipe

**Comment by tonyxty** [comment]
I think this is the same issue as #31 .  Executing any command will cause coquille to try to write to the pipe, which is broken after failing to launch coqtop.  You may need to look more carefully at startup to see the "Fatal error" message because it might appear in the midst of the buffer.

**Comment by civiclabsconsulting** [comment]
Any progress on this? Need help?
