### ISSUE TITLE
On `Admitted`: AttributeError: 'Option' object has no attribute 'split'

### ISSUE THREAD

**Issue by alexeicolin** [the-lambda-church/coquille#51]
Minimal example:

```
Theorem plus_swap : forall n m p : nat, 
  n + (m + p) = m + (n + p). 
Proof. 
  Admitted.
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/acolin/.vim/bundle/coquille/autoload/coquille.py", line 113, in coq_to_cursor
    send_until_fail()
  File "/home/acolin/.vim/bundle/coquille/autoload/coquille.py", line 352, in send_until_fail
    refresh()
  File "/home/acolin/.vim/bundle/coquille/autoload/coquille.py", line 181, in refresh
    show_info()
  File "/home/acolin/.vim/bundle/coquille/autoload/coquille.py", line 242, in show_info
    lst = info_msg.split('\n')
AttributeError: 'Option' object has no attribute 'split'

```

Silly workaround without digging into it:
```
--- autoload/coquille.py        2017-02-24 19:18:16.172890241 -0500
+++ /tmp/coquille.py    2017-02-24 19:22:42.111095494 -0500
@@ -239,7 +239,7 @@
 
     del buff[:]
     if info_msg is not None:
-        lst = info_msg.split('\n')
+        lst = str(info_msg).split('\n')
         buff.append(map(lambda s: s.encode('utf-8'), lst))
 
 def clear_info():
```

**Comment by stepchowfun** [comment]
I am having this problem as well. I am using Coq 8.6, neovim 0.1.7, Python 2.7.10.
