### ISSUE TITLE
Python Error: IndexError: list index out of range

### ISSUE THREAD

**Issue by Kraks** [the-lambda-church/coquille#65]
When running command CoqNext or CoqToCursor, python just crashed and told me an error. By the way, I'm using coq 8.5pl3, python 2.7.13 and vim 8.0.142.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kraks/.vim/bundle/coquille/autoload/coquille.py", line 129, in coq_next
    send_until_fail()
  File "/Users/kraks/.vim/bundle/coquille/autoload/coquille.py", line 321, in send_until_fail
    response = CT.advance(message, encoding)
  File "/Users/kraks/.vim/bundle/coquille/autoload/coqtop.py", line 250, in advance
    r = call('Add', ((cmd, -1), (cur_state(), True)), encoding)
  File "/Users/kraks/.vim/bundle/coquille/autoload/coqtop.py", line 200, in call
    response = get_answer()
  File "/Users/kraks/.vim/bundle/coquille/autoload/coqtop.py", line 181, in get_answer
    messageNode = parse_value(c[2])
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 266, in __getitem__
    return self._children[index]
IndexError: list index out of range
```

**Comment by lrabenau** [comment]
Having a similar issue.. did anybody solve this?
